reddit_clone/config/routes.rb
Rails.application.routes.draw do
  resources :taggings
  root 'links#index'
  resources :links do
    member do
      get 'upvote'
      get 'downvote'
      get 'new'
      get 'visit'
    end
  end
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :tags, only: [:show]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings


  def tag_names
    tags.collect(&:name).join(", ")
  end
end

reddit_clone/app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings
  has_many :links, through: :taggings

end

reddit_clone/app/models/tagging.rb
class Tagging < ApplicationRecord

  belongs_to :link
  belongs_to :tag

   validates_presence_of :link, :tag

end

reddit_clone/app/models/user.rb
class User < ApplicationRecord
  has_many :links
  has_secure_password
  

  # validates :username, :email_address,
  #           presence: true,
  #           uniqueness: true
  #
  # validates :email_address,
  #           format: /\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\b/
end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def logged_out?
    !current_user
  end

  def require_login
    redirect_to :root if logged_out?
  end

  def forbid_login
    flash[:warning] = "You are currently logged in!" if current_user
    redirect_to :root if logged_in?
  end

end

# def forbid_login
#   if current_user
#   flash[:warning] = "You are currently logged in!"
#   redirect_to :root
# end

reddit_clone/app/controllers/links_controller.rb
class LinksController < ApplicationController


  def index
    @links = Link.all.order(votes: :desc)
  end


  def new
    @links = Link.new
  end

  def create
    if current_user
    @links = Link.new(links_params)
    @links.votes = 1
    @links = current_user.links.new(links_params)
    if @links.save
      tag_names = params[:link][:tag_names].split(",")
      tag_names = tag_names.collect(&:strip)
      tag_names.each do |name|
        @links.tags << Tag.find_or_initialize_by(name: name)
      end
      flash[:success] = "Your link is posted!"
      redirect_to root_path
    else
      render :new
    end

    else
      flash[:warning] = "You must be logged in to Post! Create an account below :)"
      redirect_to new_user_path
    end

  end

  def upvote
    if current_user
    @links = Link.find(params[:id])
    @links.votes = 0 unless @links.votes
    @links.votes += 1
    @links.save
    redirect_to :root
  else
    flash[:warning] = "You must be logged in to Upvote!"
    redirect_to login_path
  end
end

  def downvote
    if current_user
    @links = Link.find(params[:id])
    @links.votes = 0 unless @links.votes
    @links.votes -= 1
    @links.save
    redirect_to :root
  else
    flash[:warning] = "You must be logged in to Downvote!"
    redirect_to login_path
  end
end


  def visit
    if current_user
    @links = Link.find(params[:id])
    @links.votes += 1
    @links.save!
    redirect_to @links.url
    end
  end

  def links_params
    params.require(:link).permit(:title, :url, :email_address)
  end

end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :forbid_login, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:sessions][:username])
    if user
      if user.authenticate(params[:sessions][:password])
        session[:user_id] = user.id
        redirect_to :root
      else
        flash.now[:warning] = "Incorrect password!"
        render :new
      end
    else
      flash[:warning] = "User does not exist!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You've been successfully loggged out :)"
    redirect_to :root
  end

end

reddit_clone/app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
end

reddit_clone/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find_by(id: params[:id])
  end

end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      flash.now[:warning] = "ah ah ah. You didn't say the magic word..."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end


end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/links_helper.rb
module LinksHelper
end

reddit_clone/app/helpers/post_helper.rb
module PostHelper
end

reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/app/helpers/taggings_helper.rb
module TaggingsHelper
end

reddit_clone/app/helpers/tags_helper.rb
module TagsHelper
end

reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <p>
        Hi, <%= current_user.username %>
      </p>
      <%= link_to "New Post", new_link_path, class: "btn btn-primary" %>
      <%= button_to "Log out", logout_path(id: "hey"), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Sign up!", :new_user %>
      <%= link_to "Log In!", :login %>
    <% end %>

    <% if flash.any? %>
      <% flash.each do |key, message| %>
      <div class="alert alert-<%= key %>" role="alert">
        <p>
          <%= message %>
        </p>
      </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/links/_link.html.erb
    <tr>
      <td>
        <%= link_to upvote_link_path(link), class: "btn btn-xs btn-block" do%>
        <i class ="glyphicon glyphicon-arrow-up"></i>
        <%end%>

        <h5 class="text-center">
          <%= link.votes %>
        </h5>

        <%= link_to downvote_link_path(link), class: "btn btn-xs btn-block" do%>
        <i class ="glyphicon glyphicon-arrow-down"></i>
        <%end%>
      </td>

      <td>
        <h1><%= link_to link.title, visit_link_path(link)%></h1>
        <p>
          Written by <%= link.user.username %>
        </p>

        <h5> Tag:
        <% link.tags.each do |tag| %>
        <%=link_to tag.name, tag_path(tag)%>
        <%end%>
      </h5>
      </td>
    </tr>

reddit_clone/app/views/links/index.html.erb
<div class="jumbotron">
  <h4 class="text-center">Welcome to Zach's...</h4>
  <h1 class="text-center">Reddit (Clone)</h1>
  <h3><%= button_to "Log-In", login_path, :method => :get %></h3>
  <h3><%= button_to "Submit", new_link_path, :method => :get %></h3>
  <h3><%= button_to "Create Account", new_user_path, :method => :get %></h3>
</div>

<table class="table">

  <tbody>
    <%@links.each do |link|%>
    <tr>
      <td>
        <%= link_to upvote_link_path(link), class: "btn btn-xs btn-block" do%>
        <i class ="glyphicon glyphicon-arrow-up"></i>
        <%end%>

        <h5 class="text-center">
          <%= link.votes %>
        </h5>

        <%= link_to downvote_link_path(link), class: "btn btn-xs btn-block" do%>
        <i class ="glyphicon glyphicon-arrow-down"></i>
        <%end%>
      </td>

      <td>
        <%=link_to(link.title, visit_link_path(link))%>
      </td>
    </tr>
    <%end%>
  </tbody>
</table>

reddit_clone/app/views/links/new.html.erb
<div class="jumbotron">
  <h4 class="text-center">Welcome to Zach's...</h4>
  <h1 class="text-center">Reddit (Clone)</h1>
</div>

<%= simple_form_for @links do |f| %>

<div>
  <!-- <%= f.association :user, label_method: :username  %> -->
</div>
<div>
  <%= f.input :title %>
</div>
<div>
  <%= f.input :url %>
</div>
<div>
  <%= f.input :tag_names %>
</div>
<%= f.submit %>
<%end%>

reddit_clone/app/views/tags/show.html.erb
  <div class="jumbotron">
  <h4 class="text-center">Welcome to Zach's...</h4>
  <h1 class="text-center">Reddit (Clone)</h1>
  <h3><%= button_to "Log-In", login_path, :method => :get %></h3>
  <h3><%= button_to "Submit", new_link_path, :method => :get %></h3>
  <h3><%= button_to "Create Account", new_user_path, :method => :get %></h3>
  </div>

  <h1><%= @tag.name.titleize %> links</h1>

  <table class="table">
  <tbody>
    <%= render @tag.links %>
  </tbody>
  </table>

reddit_clone/app/views/users/_form.html.erb
<div class="jumbotron">
  <h4 class="text-center">Welcome to Zach's...</h4>
  <h1 class="text-center">Reddit (Clone)</h1>
  </div>
  <%= simple_form_for user do |f| %>
  <%= f.input :username %>
  <%= f.input :email_address %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit %>
<% end %>


<!--OR: This is the old form-->

<!-- <%= simple_form_for @user do |f| %>
<div>
    <%= f.input :username  %>
    <%= f.input :password %>
</div>
<%= f.submit %>
<%end%> -->

reddit_clone/app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.username %>
    </li>
  <% end %>
</ul>

reddit_clone/app/views/users/new.html.erb
<%= render 'form', user: @user %>